services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codex_app
    ports:
      - "8501:8501"
    depends_on:
      - pdf_vector_service
    restart: unless-stopped
    networks:
      - default

  pdf_vector_service:
    image: vectorstore_service_image
    container_name: vectorstore_service
    expose:
      - "5000"
    environment:
      - VSTORE_ENV=production
    restart: unless-stopped
    networks:
      - default
