- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.3.7
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

- repo: local
  hooks:
      - id: poetry-lock
        name: Update Poetry Lock
        entry: ./update_poetry_lock.sh
        language: script
        always_run: true
        pass_filenames: false
